default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0
  
development:
  <<: *default
  database: svmap_development

test:
  <<: *default
  database: svmap_test

production:
  <<: *default
  database: svmap_production
  username: svmap
  password: <%= ENV['SVMAP_DATABASE_PASSWORD'] %>
